development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://uepefxuceruqjo:x2tk1lm8iHa0u2aov-I-0b2WOo@ec2-54-243-248-181.compute-1.amazonaws.com:5432/d8luk84kp1g758
